### ISSUE TITLE
Express gateway and keycloak plugin

### ISSUE THREAD

**Issue by clewmas** [gitfish/express-gateway-keycloak#6]
Hello,

I'm trying to install an [express gateway and keycloak plugin](https://github.com/rajatk16/express-gateway-keycloak/blob/master/docs/express-gateway.md#installing-express-gateway-and-our-keycloak-plugin). 

When I use: `eg plugins install keycloak`.

I get the following error message:
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
C:\xxxx\keycloak-expressgateway\eg-sample\node_modules\keycloak\keycloak.min.js:1
!function(e,r){var t=function(r){function n(){return"/"==g.authServerUrl.charAt(g.authServerUrl.length-1)?g.authServerUrl+"realms/"+encodeURIComponent(g.realm):g.authServerUrl+"/realms/"+encodeURIComponent(g.realm)}function o(){return e.location.origin?e.location.origin:e.location.protocol+"//"+e.location.hostname+(e.location.port?":"+e.location.port:"")}function s(e,r){var t=e.code,o=e.error,s=e.prompt;if(t){var c="code="+t+"&grant_type=authorization_code",i=n()+"/protocol/openid-connect/token",u=new XMLHttpRequest;u.open("POST",i,!0),u.setRequestHeader("Content-type","application/x-www-form-urlencoded"),g.clientId&&g.clientSecret?u.setRequestHeader("Authorization","Basic "+btoa(g.clientId+":"+g.clientSecret)):c+="&client_id="+encodeURIComponent(g.clientId),c+="&redirect_uri="+e.redirectUri,u.withCredentials=!0,u.onreadystatechange=function(){if(4==u.readyState)if(200==u.status){var e=JSON.parse(u.responseText);a(e.access_token,e.refresh_token,e.id_token),g.onAuthSuccess&&g.onAuthSuccess(),r&&r.setSuccess()}else g.onAuthError&&g.onAuthError(),r&&r.setError()},u.send(c)}else o&&("none"!=s?(g.onAuthError&&g.onAuthError(),r&&r.setError()):r&&r.setSuccess())}function c(e){var t,n=f();if(r?"string"==typeof r&&(t=r):t="keycloak.json",t){var o=new XMLHttpRequest;o.open("GET",t,!0),o.setRequestHeader("Accept","application/json"),o.onreadystatechange=function(){if(4==o.readyState)if(200==o.status){var e=JSON.parse(o.responseText);g.authServerUrl=e["auth-server-url"],g.realm=e.realm,g.clientId=e.resource,g.clientSecret=(e.credentials||{}).secret,n.setSuccess()}else n.setError()},o.send()}else{if(!r.url)for(var s=document.getElementsByTagName("script"),c=0;c<s.length;c++)if(s[c].src.match(/.*keycloak\.js/)){r.url=s[c].src.substr(0,s[c].src.indexOf("/js/keycloak.js"));break}if(!r.realm)throw"realm missing";if(!r.clientId)throw"clientId missing";g.authServerUrl=r.url,g.realm=r.realm,g.clientId=r.clientId,g.clientSecret=(r.credentials||{}).secret,n.setSuccess()}return n.promise}function a(e,r,t){if(e){g.token=e,g.tokenParsed=i(e);var n=g.realm+"/"+g.tokenParsed.sub;g.tokenParsed.session_state&&(n=n+"/"+g.tokenParsed.session_state),g.sessionId=n,g.authenticated=!0,g.subject=g.tokenParsed.sub,g.realmAccess=g.tokenParsed.realm_access,g.resourceAccess=g.tokenParsed.resource_access}else delete g.token,delete g.tokenParsed,delete g.subject,delete g.realmAccess,delete g.resourceAccess,g.authenticated=!1;r?(g.refreshToken=r,g.refreshTokenParsed=i(r)):(delete g.refreshToken,delete g.refreshTokenParsed),t?(g.idToken=t,g.idTokenParsed=i(t)):(delete g.idToken,delete g.idTokenParsed)}function i(e){switch(e=e.split(".")[1],e=e.replace("/-/g","+"),e=e.replace("/_/g","/"),e.length%4){case 0:break;case 2:e+="==";break;case 3:e+="=";break;default:throw"Invalid token"}return e=(e+"===").slice(0,e.length+e.length%4),e=e.replace(/-/g,"+").replace(/_/g,"/"),e=decodeURIComponent(escape(atob(e))),e=JSON.parse(e)}function u(){for(var e=[],r="0123456789abcdef",t=0;36>t;t++)e[t]=r.substr(Math.floor(16*Math.random()),1);e[14]="4",e[19]=r.substr(3&e[19]|8,1),e[8]=e[13]=e[18]=e[23]="-";var n=e.join("");return n}function l(){var e="<id: "+g.callback_id++ +Math.random()+">";return e}function d(e){if(-1!=e.indexOf("?")){var r={};r.newUrl=e.split("?")[0];var t=e.split("?")[1],n=t.indexOf("#");-1!=n&&(t=t.substring(0,n));for(var o=t.split("&"),s=0;s<o.length;s++){var c=o[s].split("=");switch(decodeURIComponent(c[0])){case"code":r.code=c[1];break;case"error":r.error=c[1];break;case"state":r.state=decodeURIComponent(c[1]);break;case"redirect_fragment":r.fragment=decodeURIComponent(c[1]);break;case"prompt":r.prompt=c[1];break;default:r.newUrl+=(-1==r.newUrl.indexOf("?")?"?":"&")+c[0]+"="+c[1]}}var a=sessionStorage.oauthState&&JSON.parse(sessionStorage.oauthState);if(a&&(r.code||r.error)&&r.state&&r.state==a.state)return delete sessionStorage.oauthState,r.redirectUri=a.redirectUri,r.fragment&&(r.newUrl+="#"+r.fragment),r}}function f(){var e={setSuccess:function(r){e.success=!0,e.result=r,e.successCallback&&e.successCallback(r)},setError:function(r){e.error=!0,e.result=r,e.errorCallback&&e.errorCallback(r)},promise:{success:function(r){return e.success?r(e.result):e.error||(e.successCallback=r),e.promise},error:function(r){return e.error?r(e.result):e.success||(e.errorCallback=r),e.promise}}};return e}function p(){var r=f();if(!S.enable)return r.setSuccess(),r.promise;if(S.iframe)return r.setSuccess(),r.promise;var t=document.createElement("iframe");S.iframe=t,t.onload=function(){var e=n();S.iframeOrigin="/"===e.charAt(0)?o():e.substring(0,e.indexOf("/",8)),r.setSuccess(),setTimeout(a,1e3*S.interval)};var s=n()+"/protocol/openid-connect/login-status-iframe.html?client_id="+encodeURIComponent(g.clientId)+"&origin="+o();t.setAttribute("src",s),t.style.display="none",document.body.appendChild(t);var c=function(e){if(e.origin===S.iframeOrigin){var r=JSON.parse(e.data),t=S.callbackMap[r.callbackId];delete S.callbackMap[r.callbackId],g.sessionId&&g.sessionId!=r.session||!r.loggedIn?(g.clearToken(),t.setError()):t.setSuccess()}};e.addEventListener("message",c,!1);var a=function(){h(),g.token&&setTimeout(a,1e3*S.interval)};return r.promise}function h(){var e=f();if(S.iframe&&S.iframeOrigin){var r={};r.callbackId=l(),S.callbackMap[r.callbackId]=e;var t=S.iframeOrigin;S.iframe.contentWindow.postMessage(JSON.stringify(r),t)}else e.setSuccess();return e.promise}function m(r){if(!r||"default"==r)return{login:function(r){return e.location.href=g.createLoginUrl(r),f().promise},logout:function(r){return e.location.href=g.createLogoutUrl(r),f().promise},accountManagement:function(){return e.location.href=g.createAccountUrl(),f().promise},redirectUri:function(e){if(e&&e.redirectUri)return e.redirectUri;if(g.redirectUri)return g.redirectUri;var r=location.href;return location.hash&&(r=r.substring(0,location.href.indexOf("#")),r+=(-1==r.indexOf("?")?"?":"&")+"redirect_fragment="+encodeURIComponent(location.hash.substring(1))),r}};if("cordova"==r)return S.enable=!1,{login:function(r){var t=f(),n="location=no";r&&"none"==r.prompt&&(n+=",hidden=yes");var o,c,a=g.createLoginUrl(r),i=e.open(a,"_blank",n);return i.addEventListener("loadstart",function(e){0==e.url.indexOf("http://localhost")&&(o=d(e.url),i.close())}),i.addEventListener("loaderror",function(e){0!=e.url.indexOf("http://localhost")&&(c=!0,i.close())}),i.addEventListener("exit",function(e){c||!o?t.setError():s(o,t)}),t.promise},logout:function(r){var t,n=f(),o=g.createLogoutUrl(r),s=e.open(o,"_blank","location=no,hidden=yes");return s.addEventListener("loadstart",function(e){0==e.url.indexOf("http://localhost")&&s.close()}),s.addEventListener("loaderror",function(e){0!=e.url.indexOf("http://localhost")&&(t=!0,s.close())}),s.addEventListener("exit",function(e){t?n.setError():(g.clearToken(),n.setSuccess())}),n.promise},accountManagement:function(){var r=g.createAccountUrl(),t=e.open(r,"_blank","location=no");t.addEventListener("loadstart",function(e){0==e.url.indexOf("http://localhost")&&t.close()})},redirectUri:function(e){return"http://localhost"}};throw"invalid adapter type: "+r}if(!(this instanceof t))return new t(r);var k,g=this,v=[],S={enable:!0,callbackMap:[],interval:5};g.init=function(t){function n(){var e=function(e){e||(r.prompt="none"),g.login(r).success(function(){u.setSuccess()}).error(function(){u.setError()})},r={};switch(t.onLoad){case"check-sso":S.enable?p().success(function(){h().success(function(){e(!1)}).error(function(){u.setSuccess()})}):e(!1);break;case"login-required":e(!0);break;default:throw"Invalid value for onLoad"}}function o(){var r=d(e.location.href);return r?(p(),e.history.replaceState({},null,r.newUrl),void s(r,u)):void(t?t.token||t.refreshToken?(a(t.token,t.refreshToken,t.idToken),S.enable?p().success(function(){h().success(function(){u.setSuccess()}).error(function(){t.onLoad&&n()})}):u.setSuccess()):t.onLoad&&n():u.setSuccess())}g.authenticated=!1,k=e.Cordova?m("cordova"):m(),t&&("undefined"!=typeof t.checkLoginIframe&&(S.enable=t.checkLoginIframe),t.checkLoginIframeInterval&&(S.interval=t.checkLoginIframeInterval),"login-required"===t.onLoad&&(g.loginRequired=!0));var i=f(),u=f();u.promise.success(function(){g.onReady&&g.onReady(g.authenticated),i.setSuccess(g.authenticated)}).error(function(){i.setError()});var l=c(r);return l.success(o),l.error(function(){i.setError()}),i.promise},g.login=function(e){return k.login(e)},g.createLoginUrl=function(e){var r=u(),t=k.redirectUri(e);e&&e.prompt&&(t+=(-1==t.indexOf("?")?"?":"&")+"prompt="+e.prompt),sessionStorage.oauthState=JSON.stringify({state:r,redirectUri:encodeURIComponent(t)});var o="auth";e&&"register"==e.action&&(o="registrations");var s=n()+"/protocol/openid-connect/"+o+"?client_id="+encodeURIComponent(g.clientId)+"&redirect_uri="+encodeURIComponent(t)+"&state="+encodeURIComponent(r)+"&response_type=code";return e&&e.prompt&&(s+="&prompt="+e.prompt),e&&e.loginHint&&(s+="&login_hint="+e.loginHint),e&&e.idpHint&&(s+="&kc_idp_hint="+e.idpHint),s},g.logout=function(e){return k.logout(e)},g.createLogoutUrl=function(e){var r=n()+"/protocol/openid-connect/logout?redirect_uri="+encodeURIComponent(k.redirectUri(e));return r},g.createAccountUrl=function(e){var r=n()+"/account?referrer="+encodeURIComponent(g.clientId)+"&referrer_uri="+encodeURIComponent(k.redirectUri(e));return r},g.accountManagement=function(){return k.accountManagement()},g.hasRealmRole=function(e){var r=g.realmAccess;return!!r&&r.roles.indexOf(e)>=0},g.hasResourceRole=function(e,r){if(!g.resourceAccess)return!1;var t=g.resourceAccess[r||g.clientId];return!!t&&t.roles.indexOf(e)>=0},g.loadUserProfile=function(){var e=n()+"/account",r=new XMLHttpRequest;r.open("GET",e,!0),r.setRequestHeader("Accept","application/json"),r.setRequestHeader("Authorization","bearer "+g.token);var t=f();return r.onreadystatechange=function(){4==r.readyState&&(200==r.status?(g.profile=JSON.parse(r.responseText),t.setSuccess(g.profile)):t.setError())},r.send(),t.promise},g.loadUserInfo=function(){var e=n()+"/protocol/openid-connect/userinfo",r=new XMLHttpRequest;r.open("GET",e,!0),r.setRequestHeader("Accept","application/json"),r.setRequestHeader("Authorization","bearer "+g.token);var t=f();return r.onreadystatechange=function(){4==r.readyState&&(200==r.status?(g.userInfo=JSON.parse(r.responseText),t.setSuccess(g.userInfo)):t.setError())},r.send(),t.promise},g.isTokenExpired=function(e){if(!g.tokenParsed||!g.refreshToken)throw"Not authenticated";var r=g.tokenParsed.exp-(new Date).getTime()/1e3;return e&&(r-=e),0>r},g.updateToken=function(e){var r=f();if(!g.tokenParsed||!g.refreshToken)return r.setError(),r.promise;e=e||5;var t=function(){if(g.isTokenExpired(e)){var t="grant_type=refresh_token&refresh_token="+g.refreshToken,o=n()+"/protocol/openid-connect/token";if(v.push(r),1==v.length){var s=new XMLHttpRequest;s.open("POST",o,!0),s.setRequestHeader("Content-type","application/x-www-form-urlencoded"),g.clientId&&g.clientSecret?s.setRequestHeader("Authorization","Basic "+btoa(g.clientId+":"+g.clientSecret)):t+="&client_id="+encodeURIComponent(g.clientId),s.onreadystatechange=function(){if(4==s.readyState)if(200==s.status){var e=JSON.parse(s.responseText);a(e.access_token,e.refresh_token,e.id_token),g.onAuthRefreshSuccess&&g.onAuthRefreshSuccess();for(var r=v.pop();null!=r;r=v.pop())r.setSuccess(!0)}else{g.onAuthRefreshError&&g.onAuthRefreshError();for(var r=v.pop();null!=r;r=v.pop())r.setError(!0)}},s.send(t)}}else r.setSuccess(!1)};if(S.enable){var o=h();o.success(function(){t()}).error(function(){r.setError()})}else t();return r.promise},g.clearToken=function(){g.token&&(a(null,null,null),g.onAuthLogout&&g.onAuthLogout(),g.loginRequired&&g.login())},g.callback_id=0};"object"==typeof module&&module&&"object"==typeof module.exports?module.exports=t:(e.Keycloak=t,"function"==typeof define&&define.amd&&define("keycloak",[],function(){return t}))}(window);

ReferenceError: window is not defined
    at Object.<anonymous> (C:\xxxx\keycloak-expressgateway\eg-sample\node_modules\keycloak\keycloak.min.js:1:11880)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at ChildProcess.<anonymous> (C:\xxxx\keycloak-expressgateway\eg-sample\node_modules\express-gateway\lib\plugin-installer.js:94:33)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
child_process.js:651
    throw err;
    ^

Error: Command failed: C:\xxxx\keycloak-expressgateway\eg-sample\node_modules\.bin\eg.cmd plugins install keycloak
    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at exports.executeInScope (C:\xxxx\AppData\Roaming\npm\node_modules\express-gateway\bin\execution-scope.js:37:5)
    at Object.exports.bootstrap (C:\xxxx\AppData\Roaming\npm\node_modules\express-gateway\bin\environment.js:11:7)
    at Object.<anonymous> (C:\xxxx\AppData\Roaming\npm\node_modules\express-gateway\bin\index.js:9:46)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6456,
  stdout: null,
  stderr: null
}

Could you please help me?

**Comment by germanllop** [comment]
A little bit late, but you need to do:

npm i -S express-gateway-keycloak
